NTI-9325: Prevent stripping of html data related to mentions and tagging.
NextThought/nti.contentfragments pull request #30
Opened 2020-06-16 22:11 UTC by hagenrd

2020-06-16 22:13 UTC, jamadden requested changes
Hardcoding these here seems wrong. Can we find a more generic, extensible solution? Maybe query for an optional utility, adapter, or subscription adapter to add additional allowed attributes?

This will also need a change note.

2020-06-17 14:45 UTC, cutz commented on src/nti/contentfragments/html.py
> +            allowed_attributes = allowed_attributes | additional_attrs_allowed
If the attributes from the utility are going to be additive, we should probably make that clear in the interface docs.

2020-06-17 14:56 UTC, jamadden approved these changes
A minor comment about types and versions from me, plus cutz's comment, and it looks good.

2020-06-17 14:56 UTC, jamadden commented on src/nti/contentfragments/interfaces.py
> +                                         value_type=TextLine(title=u"The attribute name"),
I'm not sure those are TextLines. They look like NativeStringLines to me.

This should probably become version 1.4.

2020-06-17 16:00 UTC, merged

2020-06-17 16:42 UTC, jamadden commented
I've pushed 1.4.0 to PyPI.

2020-06-17 16:44 UTC, hagenrd commented
Much appreciated.